-- DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
    customer_id INT PRIMARY KEY,
    age INT,
    gender VARCHAR(10),
    item_purchased VARCHAR(50),
    category VARCHAR(50),
    purchase_amount INT,
    location VARCHAR(50),
    size VARCHAR(10),
    color VARCHAR(30),
    season VARCHAR(20),
    review_rating DECIMAL(3,1),
    subscription_status VARCHAR(10),
    shipping_type VARCHAR(20),
    discount_applied VARCHAR(10),
    promo_code_used VARCHAR(10),
    previous_purchases INT,
    payment_method VARCHAR(30),
    frequency_of_purchases VARCHAR(30)
);

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, sum(purchase_amount) AS revenue FROM customer
	GROUP BY gender;
	
--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT  customer_id, purchase_amount
FROM customer
WHERE purchase_amount >= (SELECT avg(purchase_amount) FROM customer);

--Q3.Which are the top product categorie with the highest average review ratings?

SELECT category, ROUND(avg(review_rating),1)AS rating FROM customer
group by category
ORDER by rating DESC
LIMIT 3;

--q4. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(avg(review_rating),1) AS Average_Product_rating
FROM customer
group by item_purchased
ORDER by Average_Product_rating DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(avg(purchase_amount),2) 
from customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select * from customer;
SELECT subscription_status, 
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS average_spend, 
ROUND(SUM(purchase_amount),2) AS total_revenue 
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;
 -- So non subscribed customers spend more in compare to average spend as well as revenue.
 
--Q6. Which 5 products have the highest percentage of purchases with discounts applied? 
SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS DISCOUNT_RATE
FROM customer
GROUP BY item_purchased
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type AS (
SELECT customer_id, previous_purchases,
	CASE 
	WHEN previous_purchases = 1 THEN 'New Customer'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning Customer'
	ELSE 'Loyal Customer'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, count(*) AS total
FROM customer_type
GROUP BY customer_segment;

select * from customer;
--Q8. What are the top 3 most purchased products within each category?
with item_counts AS (
SELECT category, 
item_purchased, 
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS total_customer
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?
SELECT 
	CASE
	    WHEN age BETWEEN 18 AND 29 THEN 'Young Adults'
	    WHEN age BETWEEN 30 AND 44 THEN 'Adults'
	    WHEN age BETWEEN 45 AND 59 THEN 'Mid-Age Adults'
	  	ELSE 'Seniors'
	END AS age_group,
		sum(purchase_amount) AS revenue,
		ROUND(100 * sum(purchase_amount) / sum(sum(purchase_amount)) OVER (),2) ::TEXT || '%' AS Contribution_percentage
		FROM customer
		GROUP BY age_group
		ORDER BY revenue DESC;
		
	




